import turtle

t = turtle.Turtle()
turtle.bgcolor('black')

t.hideturtle()


def firstcircle():
     t.up()
     t.pensize(10)
     t.begin_fill()
     t.fillcolor('red')
     t.color("red")
     t.goto(0,-200)
     t.down()
     t.circle(200)
     t.end_fill()

def firstcutout():
     t.up()
     t.goto(0,-180)
     t.pensize(2)
     t.color("black")
     t.down()
     t.fillcolor("black")
     t.begin_fill()
     t.circle(180)
     t.end_fill()

def letter():
     t.up()
     t.goto(-200,-225)
     t.pensize(7)
     t.color("silver")
     t.fillcolor("silver")
     t.down()
     t.begin_fill()
     t.left(65)
     t.fd(550)
     t.right(65)
     t.fd(64)
     t.right(90)
     t.fd(375)
     t.right(90)
     t.fd(64)
     t.right(90)
     t.fd(56)
     t.left(90)
     t.fd(70)
     t.left(68)
     t.fd(195)
     t.right(68)
     t.fd(89)
     t.end_fill()

def lettercutout():
     t.up()
     t.pensize(1)
     t.color('black')
     t.fillcolor("black")
     t.goto(-15,15)
     t.right(180)
     t.down()
     t.begin_fill()
     t.fd(45)
     t.left(90)
     t.fd(125)
     t.left(160)
     t.fd(133)
     t.end_fill()

def outline():
     t.up()
     t.goto(-211.4,-225)
     t.color('black')
     t.pensize(13)
     t.setheading(0)
     t.left(65)
     t.down()
     t.fd(200)
     t.bk(205)
     t.right(65)
     t.fd(112)
     t.left(68)
     t.fd(100)

def cutline():
     t.up()
     t.goto(25,50)
     t.down()
     t.pensize(14)
     t.color('black')
     t.setheading(0)
     t.right(40)
     t.fd(112)
     t.right(105)
     t.fd(112)



firstcircle()
firstcutout()
letter()
lettercutout()
outline()
cutline()

turtle.done()